"""Add api_key to APIModel

Revision ID: 78ed842c38ba
Revises: 3c3561ca9eff
Create Date: 2025-04-26 20:56:34.690598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ed842c38ba'
down_revision = '3c3561ca9eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_model', schema=None) as batch_op:
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
